version: '3.9'


services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mysql:
    build: https://github.com/p2vvel/docker_f1_db_ergast.git
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  redis:
    image: redis
  api:
    build: .
    command: "python -m gunicorn --bind 0.0.0.0:8000 f1_api.wsgi"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=f1_api.production
      